BASE_URL = https://regoffice.senla.eu/

# Login user to app
USERNAME = user
PASSWORD = senlatest

# Credential to DB
DB_URL = jdbc:postgresql://192.168.1.93:5432/register_office
DB_USERNAME = user
DB_PASSWORD = user_senla